apiVersion: v1
kind: Service
metadata: 
  name: multipodService
  labels:
    app: servicePod
spec:
  type: NodePort
  selector: 
    app: multicontainer-pod #label of the pod that contains the application
  ports: 
    - protocol: TCP
      port: 80 #a virtual port no of the service tells to direct traffic coming from nodePort to targetPort
      targetPort: 80 #actual port of the container on which the app is listening 
      nodePort: 32001 #the port on which the call from the browser will be made