apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-single-comtainer
  labels:
    app: nginx-pod
spec:
  containers:
    - name: nginx-containers
      image: nginx:latest
      ports:
        - containerPort: 80