#code for the deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1-pod
  template:
    metadata:
      labels:
        app: app1-pod
    spec:
      containers:
      - name: app1-container
        image: akhilkumar119/app1-image:v1
        ports:
        - containerPort: 80

---

#ccode for the service file 
apiVersion: v1
kind: Service
metadata:
  name: app1-service #this service name will be referenced in the ingress controller yaml file
spec:
  selector:
     app: app1-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
