apiVersion: v1
kind: Service
metadata:
  name: canary-common-service
  namespace: canary-namespace
spec:
  type: LoadBalancer
  selector:
    app: nginx-server
  ports:
    - port: 80
      targetPort: 80
